MUI - Card component
aTmb405/breads-client pull request #107
Opened 2021-10-31 15:55 UTC by hjpunzalan

Convert card component to MUI

2021-11-01 03:48 UTC, aubundy requested changes
Looks pretty good! Just a few changes to remove a few html tags and to split the card header from the card content

2021-11-01 03:48 UTC, aubundy commented on src/common/Card.tsx
> +        {image ? (
Everything in this conditional statement is a part of the card header. Check out MUI's [Card Header](https://mui.com/api/card-header/#main-content) for this. Also, the [Avatar](https://mui.com/components/avatars/) and [Typography](https://mui.com/components/typography/) components will be helpful for the image and div, h4, and h3 html tags

2021-11-03 22:54 UTC, hjpunzalan reviewed
Card Header, Typography, Avatar components added.
Link with NavLink also added - tested and works

2021-11-04 01:05 UTC, aubundy requested changes
Looks good! I think there's only one change and one addition to be made

2021-11-04 01:05 UTC, aubundy commented on src/features/subscriptions/actions.ts
> +  userFollowers,
Since this object key changed in the action, it needs to be updated in the reducer as well. This is causing a user's followings/followers to be undefined

2021-11-04 01:05 UTC, aubundy commented on src/features/user/UserAside.tsx
> +      totalBooks = Math.round(totalWords * 1e2) / 1e2;
Would `Number(totalWords.toFixed(2))` work the same? If so, let's do that

2021-11-08 18:14 UTC, aubundy approved these changes

2021-11-08 18:15 UTC, aubundy commented
@hjpunzalan Thanks for doing this! I'll work on resolving the conflicts tonight and get this merged

2021-11-09 04:55 UTC, merged