Handle image load failure
aTmb405/breads-client pull request #97
Opened 2021-10-15 03:56 UTC by mcflav

Fixes #87 

![image](https://user-images.githubusercontent.com/52865683/137430004-8756568e-6073-47bf-a75f-85ef6bfd890c.png)

2021-10-16 19:52 UTC, aubundy commented on src/features/globalReadings/components/ListItem.tsx
> +              onError={(e) => {
Can you move this anonymous function inside `imageOnErrorHandler()` and then move that function to be within `ListItem` below `getImageDimensions()`?

2021-10-16 19:53 UTC, aubundy commented on src/features/globalReadings/components/ListItem.tsx
> +              // alt='Article'
Please remove this comment

2021-10-16 19:53 UTC, aubundy commented on src/features/globalReadings/components/ListItem.tsx
> +              //onError={imageOnErrorHandler}
Please remove this commented out code

2021-10-16 19:53 UTC, aubundy commented on src/features/globalReadings/components/ListItem.tsx
> +const imageOnErrorHandler = (
See note on this function above

2021-10-16 19:54 UTC, aubundy requested changes
This code works for me! I just added a few changes to move the logic around

2021-10-16 19:58 UTC, aubundy commented
[Image of working code](https://github.com/zero-to-mastery/breads-client/issues/87#issuecomment-943965265)

2021-10-18 01:52 UTC, mcflav commented
This has been completed. Please review, thanks!

________________________________
From: Austin Bundy ***@***.***>
Sent: Saturday, October 16, 2021 3:53 PM
To: zero-to-mastery/breads-client ***@***.***>
Cc: mcflav ***@***.***>; Mention ***@***.***>
Subject: Re: [zero-to-mastery/breads-client] Breads client update (#97)


@aubundy commented on this pull request.

________________________________

In src/features/globalReadings/components/ListItem.tsx<https://github.com/zero-to-mastery/breads-client/pull/97#discussion_r730306202>:

>                onLoad={measure}
-              alt="Article"
+              // alt='Article'


Please remove this comment

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/zero-to-mastery/breads-client/pull/97#pullrequestreview-781385681>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMTKVEYNXTII4FKRIANBLE3UHHJ3LANCNFSM5GBCPUSA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-10-20 03:47 UTC, closed without merging